### ISSUE TITLE
转载沟通 

### ISSUE THREAD

**Issue by hehonghui** [yuxingxin/RxJava-Essentials-CN#2]
hi , yuxingxin , 你好，我是开发技术前线的站长MrSimple，我们最近想翻译 《RxJava-Essentials》这本书，但是发现你已经搞定了，非常感谢你的付出。我们希望能够将你的劳动成果发布在开发技术前线上，我们会保留你的原文链接以及你的github项目链接，不知道是否可以 ？另外，欢迎加入我们的翻译组，期待你的回复，谢谢 ~  😊

github 项目 : https://github.com/bboyfeiyu/android-tech-frontier/ 
开发技术前线 : http://www.devtf.cn

**Comment by yuxingxin** [comment]
@bboyfeiyu 多谢MrSimple，没问题，希望扩散给更多的人，更荣幸能加入翻译组，其实我也是开发技术前线的粉丝，嘿嘿

**Comment by hehonghui** [comment]
好的哈，那我按照这期就发布你这本书好了。谢啦   。这是我们的翻译群 399424408 ，可以加一下    :)

在 2016年1月5日 上午11:08，Sean Liu notifications@github.com写道：

**Comment by hehonghui** [comment]
@yuxingxin 你能把gitbook的那个目录截图给我一份么，我看看每一章对应的有哪些markdown，然后整理成每章节一个文件发布出去。然后给出你的gitbook地址。

**Comment by yuxingxin** [comment]
@bboyfeiyu MrSimple 我把目录给重新整理了，这样应该就看的很清楚了

**Comment by inferjay** [comment]
@yuxingxin 这个翻译有经过作者的授权吗？

**Comment by yuxingxin** [comment]
@inferjay 已经和作者联系过了，现在正在和出版社沟通中

**Comment by inferjay** [comment]
@yuxingxin 赞，干的漂亮
