### ISSUE TITLE
示例代码的问题

### ISSUE THREAD

**Issue by xiaozhi003** [yuxingxin/RxJava-Essentials-CN#6]
不得不说原书的第一个示例写的就阻塞了线程，打开Activity(Fragement)就需要等待一段时间；后来发现解析图片没有放到io线程中，自行修改好使了；不知道是不是作者写的时候手抖了，哈哈：），如果真要出中文版的话还是希望把示例代码都过一遍（ps：可以稍作修改），以免给初学者造成麻烦以为它并不如想象中的好用；谢谢作者 @yuxingxin 翻译了这么好的东东；还是那句话：开源万岁——；

**Comment by yuxingxin** [comment]
@xiaozhi003 嗯嗯，作者的思路可能是因为没有讲到异步，所以呢就不想引入这个知识点，不过你在练习的时候也可以参考这个库的示例代码，或许对你有帮助：https://github.com/marcoRS/rxjava-essentials

**Comment by xiaozhi003** [comment]
貌似他这个就是原书的示例代码，不过还是谢谢了

**Comment by Bronts** [comment]
正好有个issue，对翻译者表示下感谢^_^

**Comment by Bronts** [comment]
顺便提个小问题吧，pdf中的文字貌似转换得有点问题，倒是不影响阅读。
![image](https://cloud.githubusercontent.com/assets/3986255/12324978/decc9df4-bb01-11e5-9c01-4ff76867a011.png)

**Comment by yuxingxin** [comment]
@Bronts 嗯嗯，谢谢指正，这好像是GitBook的问题，咱们也没有办法，所以如果特别在意的话可以在线看哈

**Comment by Knight-ZXW** [comment]
英语不好，看英文文档好吃力

**Comment by doritoswb** [comment]
谢谢@yuxingxin大神翻译出这么好的东西，麻烦问一下，哪里可以下载到这些源码呢？

**Comment by yuxingxin** [comment]
https://github.com/hamen/rxjava-essentials
