### ISSUE TITLE
不存在Observable.throw()方法。

### ISSUE THREAD

**Issue by deviltsw** [yuxingxin/RxJava-Essentials-CN#8]
翻译辛苦了，第二章最后面说的：

>  [我们也可以使用throw()创建一个不发射数据并且以错误结束的Observable
> ](https://github.com/yuxingxin/RxJava-Essentials-CN/blob/master/chapter2/observable.md)

在RxJava最新版中不存在这个方法，而是用[Observable.error(Throwable)](https://github.com/ReactiveX/RxJava/wiki/Creating-Observables)代替。

**Comment by yuxingxin** [comment]
@deviltsw 是的，可能作者写这本书的时候还是throw方法

**Comment by yuxingxin** [comment]
@deviltsw 我觉得作者的意思不是特指Java语言，如果是针对Java语言的实现就是用error方法，用throw做统称，它在各个语言都有实现，详情请看官方文档：http://reactivex.io/documentation/operators/empty-never-throw.html

**Comment by deviltsw** [comment]
@yuxingxin 有可能，不过很容易造成误导。
