### ISSUE TITLE
defer的讲解

### ISSUE THREAD

**Issue by tinggengyan** [yuxingxin/RxJava-Essentials-CN#9]
在第三章[defer](https://github.com/yuxingxin/RxJava-Essentials-CN/blob/master/chapter3%2Fa_few_more_examples.md)的讲解例子中

``` java
private Observable<Integer> getInt(){
    return Observable.create(subscriber -> {
        if(subscriber.isUnsubscribed()){
            return;
        }
        App.L.debug("GETINT");
        subscriber.onNext(42);
        subscriber.onCompleted();
    });
}
```

提到"deferred存在，但是getInt() create()方法还没有调用:logcat日志也没有“GETINT”打印出来:"
言下之意是延迟了call方法，如果不用defer延迟则会打印出这个log；按照理解，是延迟了observable的创建，我觉得应该将App.L.debug("GETINT");放到return 之前

``` java
private Observable<Integer> getInt(){
   App.L.debug("GETINT");
    return Observable.create(subscriber -> {
        if(subscriber.isUnsubscribed()){
            return;
        }
        subscriber.onNext(42);
        subscriber.onCompleted();
    });
}
```

不知道我的理解对不对？

**Comment by yuxingxin** [comment]
这里猜测作者用打印Log的方式来说明getInt()函数的执行，即发射数据42，如果放在return前，就无论如何都会立即执行，那么就起不到讲defer的本意了
